### ISSUE TITLE
Gnome 45 support?

### ISSUE THREAD

**Issue by DuttaAB-dev** [FelipeFTN/emoji-copy#11]

**Comment by FelipeFTN** [comment]
Working on it! 😅

**Comment by DuttaAB-dev** [comment]
I just started learning JS. Lemme know if I can help you in any way!

**Comment by FelipeFTN** [comment]
Of course, dude!
Here is the new Gnome 45 port documentation: [gjs.guide](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils).
This doc explains how to correctly migrate the Gnome extension to Gnome 45.
Since the gnome-45 branch still in progress, it would be very useful if you could review if the changes are correct.
I will open a PR on this branch, so you can review the changes better.
Feel free to look if there is any error, missing import or if some import path does not exist! 😀👍
Here's the PR #12 🎉
Feel free to review and send comments on it!

**Comment by BloodyIron** [comment]
So uh yeah can we get Gnome 45 mainlined already please? The extension page site still only lists 44 supported :/

**Comment by ctrueden** [comment]
@BloodyIron If you read through the changes in #12, you will see that the work is complicated. GNOME 45 requires major reworking of the codebase. Please be patient, or else help out to make the development go faster.

**Comment by FelipeFTN** [comment]
@BloodyIron Hello Buddy! I would be so happy if the problem was just adding the new Gnome version to the extension and deploying it :smile: 
But Unfortunately, Gnome changed a lot how the extensions should be made. The migration to the Gnome 45 is taking a long time, it's being almost a refactor :skull: 
But don't worry, I'm still working on it! :tada: 
I'm just joined some Gnome IRC channels, and I'm getting some help there! Hopefully I will finish it soon! :rocket:

**Comment by BloodyIron** [comment]
Alright well I appreciate the help from all involved! And no worries about however long it takes, more just throwing my hat into the ring and shouting "Me too please!", or something like that 😅😅

I do see from other extensions that generally all have a bunch of work needed to reach GNOME 45. 🤓

Anyways, quite like this extension, so I'm looking forward to the '45 release! 🍿🍿🍿🍿🍿🍿❤️❤️❤️

**Comment by p134c0d3** [comment]
@FelipeFTN what can I do to help? I know JS, TS. Same as you told @DuttaAB-dev ? Review changes? This would be my first Gnome contribution so I'll dive into the Gnome docs for this and see what I can pick up pretty quick. Only thing I'd need is a direction for you to point me 🙂

**Comment by FelipeFTN** [comment]
**Hello Buddy! Thank you so much! :tada:** 
Good news! I just finished the migration, now I'm just fixing some bugs :rocket: 
Thank you so much for your offer to help. I'm finishing the migration already, but be sure, there is a lot of work to do in this project hahaha :sweat_smile:
I will be updating here soon!
One quick update is that the extension settings page was killed :hocho: We were not using that much, and I don't know how to migrate it to GTK, so I just deleted from now :sweat_smile:
**In a couple of days it will be available on Gnome Extension store!! :tada:**

**Comment by p134c0d3** [comment]
@FelipeFTN  Great! Glad to hear it! Love the extension. 🙂  Do you have a list of to-do's for contributors to look at should they decide to jump in?
Yeah I can't say that I ever opened the settings page personally aside from when I installed it. It just worked!

**Comment by p134c0d3** [comment]
Thank you for the response @FelipeFTN ! I will take a look at this when I have some free time later and see what I can dive into. 🙂
