### ISSUE TITLE
Keybinding appears to have changed and also can no longer be configured?

### ISSUE THREAD

**Issue by psycotica0** [FelipeFTN/Emoji-Copy#15]
## Bug Report

**Current Behavior**
The new Gnome 45 compatible emoji picker opens when you hit "Super+."

**Expected behavior/code**
The picker opens when I hit "Super+E"

**Environment**
- emoji-copy version(s): 12

**Possible Solution**
Configurable would be nice, but if that doesn't work it could just be hardcoded to _my_ preference 😅

(Oh, in putting that emoji in, I found out it also doesn't close when I pick the emoji I wanted, which I think the old one also did? Was that also a preference before?)

**Comment by FelipeFTN** [comment]
Hello friend! Thank you for your bug report! :space_invader:
I will be working on a new preferences window, since the old one got deprecated after the Gnome 45 migration :sweat_smile:
But don't worry, until there, you can do this to make this works:
1. Go to `~/.local/share/gnome-shell/extensions/emoji-copy@felipeftn/`
2. Edit the file `schemas/org.gnome.shell.extensions.emoji-selector.gschema.xml`
3. Go to line 54 and change the default key to `<Super>e`
4. recompile the settings: `glib-compile-schemas ~/.local/share/gnome-shell/extensions/emoji-copy@felipeftn/schemas`

This should do the job :pray: :smile: 
Let me know if it works!

**Comment by gaussandhisgun** [comment]
got here because i wanted to make the status icon hidden by default, editing the schemes does actually work, thanks! i'm looking forward for a new config window, thanks for bringing my favorite emoji picker on gnome 45!

**Comment by psycotica0** [comment]
Awesome! That works good enough for me! Thanks so much for putting the work into porting this forward!

**Comment by psycotica0** [comment]
Just got updated to the new version. Works well for me. Thanks!

**Comment by FelipeFTN** [comment]
**Great to hear that!** Thank you for reporting this issue! :100:
