### ISSUE TITLE
White boxes instead of emojis

### ISSUE THREAD

**Issue by ptrne** [FelipeFTN/Emoji-Copy#81]
## Bug Report

**Current Behavior**
After having installed the extension, emojis are not displayed. Instead, white boxes are.
![image](https://github.com/user-attachments/assets/70777403-f0dc-4a2d-8c6a-fca40b304a7d)

**Expected behavior/code**
Emojis should be displayed like usual.

**Environment**

- emoji-copy version(s): 25
- OS: Gentoo Linux 23 with Kernel 6.6.62
- GNOME: 46

Any hints would be appreciated :+1:

**Comment by ptrne** [comment]
Update: I installed the Google Noto fonts and activated them --> Problem went away. So I figure it has something to do with the default font selected by the system.

**Comment by FelipeFTN** [comment]
**Hello buddy! @ptrne Thank you for reporting this issue!** 

Yes, you need to have some emoji font installed in your system for **Emoji-Copy** to work properly! :100:
Google Noto fonts works well, but you also could use any other font with emoji characters, like this one for example: https://github.com/13rac1/twemoji-color-font. Which is the font recommended in the `README.md` file! :tada:

Feel free to post any comments here, or close the issue since it was correctly solved! 👍 

**Thanks! ❤️**
